### ISSUE TITLE
FileNotFoundError on first run

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-cli-archived#172]
**Describe the bug**
Installed 0.1.6 on Windows 10. After installation, ran `mgc login --scopes "user.read.all"`. Got:

```
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msgraph/cli/core/profile.py", line 25, in write_profile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jasonjoh\\.mg\\profile.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Msgraph\CLI\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Msgraph\CLI\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msgraph/cli/__main__.py", line 52, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msgraph/cli/__main__.py", line 47, in cli_main
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msgraph/cli/__main__.py", line 29, in create_profile_if_none_exists
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msgraph/cli/core/profile.py", line 28, in write_profile
msgraph.cli.core.exceptions.CLIException: An error occured while creating your profile
```

**To Reproduce**
1. Install 0.1.6 on Windows 10
2. Run `mgc login --scopes "user.read.all"`

**Expected behavior**
Command completes without error.

**Additional context**
I noticed that the file it says isn't found references a `.mg` folder in my user profile. There's a `.mgc` folder that was created during the install. Is this just a typo somewhere?
 
[AB#10533](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10533)

**Comment by jasonjoh** [comment]
Sure enough - I created a `.mg` folder in my %USERPROFILE% directory and the command worked.
